server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentification_db
    username: postgres
    password: Passer@123!!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  h2:
    console.enabled: true

security:
  jwt:
    secret: "change-me-super-secret-256bits-minimum-change-me"
    access-expiration-minutes: 15
    refresh-expiration-days: 7
