server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Passer@123!!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
