server:
  servlet:
    context-path: /api/v1/isi  # préfixe pour tous les endpoints

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: postgres
    password: Passer@123!!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # crée ou met à jour les tables automatiquement
    show-sql: true       # affiche les requêtes SQL dans la console
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always       # exécuter data.sql au démarrage

springdoc:
  default-consumes-media-type: application/json
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
